
var myApp = angular.module("myApp", [

    "ngRoute",
    "ngCookies",
    "angular-loading-bar",
    "ngAnimate",
    "toastr",
    "ui.bootstrap",
    "datatables",
    "datatables.bootstrap",
    "datatables.buttons",
    "AuthenticationModule",
    "PublicationModule",
    "CourseModule",
    "SubjectModule",
    "BookModule",
    "UserModule",
    "IssueBookModule",
    "ReturnBookModule",
    "LostOrReplaceModule",
    "StatisticsModule",
    "SearchModule",
    "RequestModule",
    "MagazineModule",
    "NewspaperModule",
    "ConfigurationModule",
    "CommitteeMemberModule",
]);

